name: trigger GitHub Actions with feature-based development

on:
  pull_request:
    branches:
        - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge  it's awesome!!!!"